### ISSUE TITLE
No se reciben datos en parking_offstreetparking_agg_hour

### ISSUE THREAD

**Issue by ignaciodomingo** [GeographicaGS/UrboCore-processing#16]
Detalles del error de AWS:
Alarm details:
              - ERROR on watcher id "parking_offstreetparking_agg_hour."
              - More than 150 minutes without receiving updates.
              - DB Environment: carto.

@josemazo, cuando lo revises avísame para ver cómo lo haces para ver si en el futuro puedo revisarlo yo antes de pasartelo.

**Comment by IgnacioDomingo** [comment]
@josemazo hay datos pero de dos horas tarde. ¿Está bien configurado el job de agregados?

**Comment by IgnacioDomingo** [comment]
creo que está puesto una hora tarde sólo, puede ser algo del cambio de hora que se hizo en octubre?

**Comment by josemazo** [comment]
Los hago a mano :(
