### ISSUE TITLE
No se reciben datos en transport_vehicle_lastdata

### ISSUE THREAD

**Issue by ignaciodomingo** [GeographicaGS/UrboCore-processing#17]
Aviso de Urbo Watcher - 
WARNING on watcher id "transport_vehicle_lastdata."
              - More than 30 minutes without receiving updates.
              - DB Environment: pgsql.

**Comment by IgnacioDomingo** [comment]
@josemazo he estado revisando, y datos siempre hay, pero de 1 hora antes. Me parece que lo que está mal puesto es el tiempo del watcher que debe comparar, o el tiempo del simulador.
