### ISSUE TITLE
No se reciben datos en parking_offstreetparking_agg_day, environment_aqobserved_agg

### ISSUE THREAD

**Issue by ignaciodomingo** [GeographicaGS/UrboCore-processing#18]
Alarm details:
              - ERROR on watcher id "parking_offstreetparking_agg_day."
              - More than 1600 minutes without receiving updates.
              - DB Environment: carto.

Urbo-Watcher report,

Alarm details:
              - ERROR on watcher id "environment_aqobserved_agg."
              - More than 1600 minutes without receiving updates.
              - DB Environment: carto.

**Comment by IgnacioDomingo** [comment]
@josemazo para parking_offstreetparking_agg_day, hay datos, pero un día tarde :S
environment_aqobserved_agg -> necesitaría la coleccion de postman para poder revisarlo, es en la BD de carto

**Comment by josemazo** [comment]
Los hago a mano :(
