### ISSUE TITLE
No se reciben datos en waste_contenedores

### ISSUE THREAD

**Issue by IgnacioDomingo** [GeographicaGS/UrboCore-processing#20]
Urbo-Watcher report,

Alarm details:
              - ERROR on watcher id "waste_contenedores."
              - More than 50 minutes without receiving updates.
              - DB Environment: pgsql.

**Comment by IgnacioDomingo** [comment]
he visto con telefónica que hay datos en su parte, con lo que parece que el fallo está en nuestra parte (o se ha cambiado el modelo de datos)

**Comment by josemazo** [comment]
![image](https://user-images.githubusercontent.com/750907/34255641-e4bf0f30-e651-11e7-9d52-7d016bceeb8f.png)

Conector y processing está bien, así que con la foto confirmamos que no entran datos en Orion desde que llegan las alarmas.

**Comment by josemazo** [comment]
Por cierto, no era Guadalajara, sino Seguimiento de Contratas de Distrito Telefónica.

**Comment by josemazo** [comment]
¬¬

**Comment by josemazo** [comment]
Subscripción caducada. Arreglado, se han comprobado de que hay datos nuevos.
